### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by usalexsantos** [tsing90/pytorch_semantic_human_matting#1]
Can I run your code without the Adobe Dataset?

My images I only have the original image and the PNG mask. Does that work?

**Comment by tsing90** [comment]
yes, you can. please follow my instructions to prepare two lists similar to 'super_img.txt' and 'super_msk.txt', then change relavant lines of code such as [here](https://github.com/tsing90/pytorch_semantic_human_matting/blob/master/data/dataset.py#L264).

I should be updating the codes to ease the use of different type of data in the near future

**Comment by usalexsantos** [comment]
I'm getting this error when I run the train command.

D:\Semantic_Human_Matting_List>python train.py --patch_size=400 --nEpochs=500 --save_epoch=5 --train_batch=8 --train_phase=pre_train_t_net
Namespace(continue_train=False, dataDir='./data/', debug=False, lr=0.0001, lrDecay=100, lrdecayType='keep', nEpochs=500, nThreads=4, patch_size=400, print_iter=1000, saveDir='./ckpt', save_epoch=5, trainData='human_matting_data', train_batch=8, train_phase='pre_train_t_net', without_gpu=False)
============> Building model ...
Traceback (most recent call last):
  File "train.py", line 379, in <module>
    main()
  File "train.py", line 244, in main
    train_data = dataset.human_matting_data(args.dataDir, args.train_phase, args.patch_size)
  File "D:\Semantic_Human_Matting_List\data\dataset.py", line 172, in __init__
    self.shuffle_data()
  File "D:\Semantic_Human_Matting_List\data\dataset.py", line 231, in shuffle_data
    assert len(self.path_bg) == len(self.path_ait)*bg_per_ait + len(self.path_dim)*bg_per_dim
AttributeError: 'human_matting_data' object has no attribute 'path_ait'

I made the change on the code but I'm still having a error.

**Comment by tsing90** [comment]
it seems you have a missing variable. please make sure you changed completely on the line of 252 and [264](https://github.com/tsing90/AIT_SHM/blob/master/data/dataset.py#L264)  etc.

my fault, i'll update the code to make things clear and straight

**Comment by kkkmax** [comment]
@tsing90 @usalexsantos Hi, , thank you very much for your project. I met some questions about data preparation during the preparation training process.

- pre_trian T_net
python train.py --patch_size=400 --nEpochs=500 --save_epoch=5 --train_batch=8 --train_phase=pre_train_t_net
![5](https://user-images.githubusercontent.com/42377340/54671586-294e7880-4b31-11e9-9eda-3883e3eb5d5c.png)

- How to generate the file "ait.txt"
![4](https://user-images.githubusercontent.com/42377340/54671733-77fc1280-4b31-11e9-806f-87cdf94d0f08.png)

**Comment by usalexsantos** [comment]
@tsing90 The Supervisely dataset has several folders (ann, img, masks_human, mansks_machine). How are you handling all this folder on the Path list?

**Comment by tsing90** [comment]
@kkkmax sorry for the messy code of data lists, I've update the data preparation methods, please read the instructions for details.

**Comment by tsing90** [comment]
@usalexsantos  in the previous code, I just kept the <img> and <machine_msk> folders, and put them into two files. Now as I updated the dataloader method, you have combine the img and mask together in order to get the RGBA image , and then generate the list file.
