### ISSUE TITLE
How about MobileNet as T-Net?

### ISSUE THREAD

**Issue by pourfard** [tsing90/pytorch_semantic_human_matting#11]
I saw that [lizhengwei1992](https://github.com/lizhengwei1992/Semantic_Human_Matting) has used MobileNet as T-Net. PSPNet is much larger and is very slow. How do you think about using MobileNet?

**Comment by tsing90** [comment]
I think it depends on your task. I tried MobileNet, for simple portrait images, it seems OK, but if your task requirement is higher, then you may have to consider a more powerful architecture.
