### ISSUE TITLE
about load pretrained model when training end to end

### ISSUE THREAD

**Issue by wrrJasmine** [tsing90/pytorch_semantic_human_matting#13]
when I training the end to end model , I can not load the pretrain model of t_net and m_net!
there is not define the t_path and m_path. but after I defined, there is another error occured.

**Comment by wrrJasmine** [comment]
the error is 'net_T' object has no attribute 'copy'

**Comment by tsing90** [comment]
bug fixed, the missing code in the class `Train_log()` has been added
