### ISSUE TITLE
Error on the new Train file.

### ISSUE THREAD

**Issue by usalexsantos** [tsing90/pytorch_semantic_human_matting#16]
I'm running the new train file and I'm getting this error message.

C:\pytorch_semantic_human_matting-master>python train.py --patch_size=400 --train_phase=pre_train_t_net --fgList /data/super_img.txt --bg_list /data/bg_list.txt --dataRatio [100,1]
============> Building model ...
Traceback (most recent call last):
  File "train.py", line 433, in <module>
    main()
  File "train.py", line 277, in main
    train_data = dataset.human_matting_data(args)
  File "C:\pytorch_semantic_human_matting-master\data\dataset.py", line 255, in __init__
    assert os.path.isfile(fg_path), "missing file at {}".format(fg_path)
AssertionError: missing file at /

My directory structure of the project:

pytorch_semantic_human_matting-master
│   README.md
│  test.py
|   train.py

└───model
│   │   extractors.py
│   │   M_Net.py
│   │   network.py
│   │   T_Net_psp.py

└───data
    │   data_util.py
    │   dataset.py
    |   gen_trimap.py
    |   super_img.txt
    |   super_msk.txt
    |   bg_list.txt
    └───super_img
    └───super_msk
    └───background

My list files look like this:
/pytorch_semantic_human_matting-master/data/super_img/adult-black-body-costume-41667.png
/pytorch_semantic_human_matting-master/data/super_img/ache-adult-depression-expression-41253.jpg
/pytorch_semantic_human_matting-master/data/super_img/active-activity-ball-exercise-41213.jpg
/pytorch_semantic_human_matting-master/data/super_img/active-athletic-exercise-female-40974.jpg
/pytorch_semantic_human_matting-master/data/super_img/active-cold-female-girl-41371.jpg
/pytorch_semantic_human_matting-master/data/super_img/adorable-baby-beautiful-boy-41000.png
/pytorch_semantic_human_matting-master/data/super_img/adult-attractive-full-body-41215.png
/pytorch_semantic_human_matting-master/data/super_img/adult-baby-background-bump-41286.png
/pytorch_semantic_human_matting-master/data/super_img/adult-background-business-computer-53508.png

I have one per line but looks like your list file you have several files on the same line.

**Comment by tsing90** [comment]
apparently, the paths in your list files are wrong, and also you used windows OS, take care of that.
