### ISSUE TITLE
test M net

### ISSUE THREAD

**Issue by Oseira** [tsing90/pytorch_semantic_human_matting#17]
Hi tsing, I am trying to use the test.py file. There is no problem with T_net but when I try with M-net I get an error: "indices and input shapes do not match: indices [1 x 64 x 225 x 400], input [1 x 64 x 224 x 400]" when trying to do the last pooling layer of the decoder. Do you know why I am getting this 2 pixels difference?

**Comment by Oseira** [comment]
it has to be a multiple of 64

**Comment by sanshibayuan** [comment]
I change the size in test.py to 512 and I still got the eroor
