### ISSUE TITLE
How did you construct bg image set

### ISSUE THREAD

**Issue by lan2720** [tsing90/pytorch_semantic_human_matting#18]
Hi tsing90, I have noticed the bg_list.txt. There is 18000 image paths. But the last image name is 000000581042.jpg, so I guess your total amount is at least 60w images and then you sample 1.8w here to use as bg set. I wonder where to collect so many images? How did you construct the set? Thank you.

**Comment by lan2720** [comment]
Or you just use coco 2014?

**Comment by tsing90** [comment]
yes, these index numbers are directly from coco 2014
