### ISSUE TITLE
Error running train.

### ISSUE THREAD

**Issue by usalexsantos** [tsing90/pytorch_semantic_human_matting#2]
I made the change to remove the Adobe Dataset and Coco. I'm only using a dataset with Image and Mask.

When running the code I'm getting this error.

python train.py --patch_size=400 --nEpochs=500 --save_epoch=5 --train_batch=8 --train_phase=pre_train_t_net
Namespace(continue_train=False, dataDir='./data/', debug=False, lr=0.0001, lrDecay=100, lrdecayType='keep', nEpochs=500, nThreads=4, patch_size=400, print_iter=1000, saveDir='./ckpt', save_epoch=5, trainData='human_matting_data', train_batch=8, train_phase='pre_train_t_net', without_gpu=False)
============> Building model ...
Dataset : file number 6
============> Loading datasets ...
============> Set optimizer ...
============> Start Train ! ...
epoch end, shuffle datasets again ...
epoch end, shuffle datasets again ...
epoch end, shuffle datasets again ...
epoch end, shuffle datasets again ...
epoch end, shuffle datasets again ...
Traceback (most recent call last):
  File "train.py", line 379, in <module>
    main()
  File "train.py", line 347, in main
    loss_ = loss_ / (i+1)
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by tsing90** [comment]
please double check this line of code:
`for i, sample_batched in enumerate(trainloader):`
