### ISSUE TITLE
hello tsing90，can you share the dataset about adobe of DIM  for study？

### ISSUE THREAD

**Issue by l2009312042** [tsing90/pytorch_semantic_human_matting#20]
my email is lijie09@mails.jlu.edu.cn   ，
i have send email to  bprice@adobe.com， and have no reply ！
looking  forward to your reply，best regards！

**Comment by tsing90** [comment]
sorry, I'm not allowed to share that dataset according to the license. usually, you should receive a reply within one week. double check your junk emails as well.
