### ISSUE TITLE
训练M-net的中间结果

### ISSUE THREAD

**Issue by songcheng** [tsing90/pytorch_semantic_human_matting#22]
![image](https://user-images.githubusercontent.com/8636528/58391571-08daf700-8069-11e9-939b-2d177c8c1dde.png)
训练4000张左右的图片，从一开始训练到最后就一直会有右图这样毛躁的结果，会是什么原因？

**Comment by tsing90** [comment]
please check your trimaps of the GT alpha, you may find out the reason

**Comment by cbyzju** [comment]
> please check your trimaps of the GT alpha, you may find out the reason

I meet the same problem, but I don't know why, I have check GT alpha and its trimap, both of them are correct.
