### ISSUE TITLE
请问效果如何

### ISSUE THREAD

**Issue by taasoo** [tsing90/pytorch_semantic_human_matting#3]
大神，请问testing的效果如何？我们在考虑是否值得尝试一下这个网络，我们有百万级的训练数据。

**Comment by tsing90** [comment]
效果还不错，取决于数据的质量。为何会有这么多数据？可否分享一些给我 ；）

**Comment by taasoo** [comment]
我们同事开源了3万多张matting数据：
https://github.com/aisegmentcn/matting_human_datasets
需要更多数据的话，可以联系他微信，上面有。

**Comment by tsing90** [comment]
谢谢，数据虽多，但无法用于精细抠图，只能用于segmentation 吧

**Comment by fzhang612** [comment]
@tsing90  请问是如何判断上面提到的3万多张的数据“无法用于精细抠图”的？

**Comment by LoveU3tHousand2** [comment]
因为这个图的Alpha和能生成的trimap都low到一b， 大致的f u b 能分但是边缘根本别想多好的效果。
