### ISSUE TITLE
M net output

### ISSUE THREAD

**Issue by judgeeeeee** [tsing90/pytorch_semantic_human_matting#6]
``` python
raw_alpha = self.conv_0(x1d)
``` 
and 
``` python
alpha_r = self.m_net(m_net_input)

# fusion module

# paper : alpha_p = fs + us * alpha_r

alpha_p = fg + unsure * alpha_r
```

alpha_p may not in [0,1]

is that trouble?

**Comment by tsing90** [comment]
you are right, my mistake, a sigmoid function should be added to the end of m-net

**Comment by LoveU3tHousand2** [comment]
And how to do that?

**Comment by LoveU3tHousand2** [comment]
> you are right, my mistake, a sigmoid function should be added to the end of m-net

Hi, 关于这个问题， 您是不是未在公布的代码中修改啊， 因为我这目前mnet的pre_train效果特别奇怪， 我找了两天的原因， 刚刚才看到条issue， 以下是我的'奇怪的结果'
![Mnet_03](https://user-images.githubusercontent.com/69668084/124703420-dcbb2100-df24-11eb-94a0-a024d914958a.jpg)
![Mnet_284](https://user-images.githubusercontent.com/69668084/124703422-de84e480-df24-11eb-9fa0-021de814c433.jpg)
![Mnet_117](https://user-images.githubusercontent.com/69668084/124703428-e17fd500-df24-11eb-8700-67ab9f7256e5.jpg)

**Comment by LoveU3tHousand2** [comment]
还希望能回复
