### ISSUE TITLE
compositing on the fly

### ISSUE THREAD

**Issue by Oseira** [tsing90/pytorch_semantic_human_matting#9]
Thank you for the great work. I am trying to understand how this project works:
If I understand correctly, the model is trained using 2 lists: one with foregrounds and one with backgrounds that are then composited on  the fly during the training.

I can't seem to understand where in the train.py code does the compositing happen?
Thanks for your help

**Comment by kkkmax** [comment]
According to the design of tsing90, I think that synthesis and then training, synthesis should be completed in the data preparation process

**Comment by tsing90** [comment]
@kkkmax is correct, that's done in the dataloader, plz refer to the file ./data/dataset.py

**Comment by Oseira** [comment]
Thank you both, I think I see how it goes now.
